//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Form2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Form2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\ШАГ\forms\ПрикладиЗКласу\Form2\img\1.jpg.
        /// </summary>
        internal static string img1 {
            get {
                return ResourceManager.GetString("img1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\ШАГ\forms\ПрикладиЗКласу\Form2\img\2.jpg.
        /// </summary>
        internal static string img2 {
            get {
                return ResourceManager.GetString("img2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\ШАГ\forms\ПрикладиЗКласу\Form2\img\3.jpg.
        /// </summary>
        internal static string img3 {
            get {
                return ResourceManager.GetString("img3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\ШАГ\forms\ПрикладиЗКласу\Form2\img.
        /// </summary>
        internal static string img4 {
            get {
                return ResourceManager.GetString("img4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\ШАГ\forms\ПрикладиЗКласу\Form2\img.
        /// </summary>
        internal static string img5 {
            get {
                return ResourceManager.GetString("img5", resourceCulture);
            }
        }
    }
}
